name: YouTube Trending Data Pipeline

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-trending-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas requests

      - name: Run Data Collection Script
        run: python fetch_trending_data.py

      - name: Upload Trending Data
        uses: actions/upload-artifact@v4
        with:
          name: youtube_trending_data
          path: youtube_trending_data.csv

  extract-keywords:
    runs-on: ubuntu-latest
    needs: fetch-trending-data  # Ensures data is fetched first
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas textblob wordcloud matplotlib

      - name: Download Trending Data
        uses: actions/download-artifact@v4
        with:
          name: youtube_trending_data
          path: .

      - name: Run Keyword Extraction Script
        run: python extract_keywords.py

      - name: Upload Word Cloud
        uses: actions/upload-artifact@v4
        with:
          name: wordcloud
          path: wordcloud.png
