name: YouTube Trending Keywords

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual execution

jobs:
  fetch-trending-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas requests nltk wordcloud matplotlib

      - name: Run Data Fetching Script
        run: python fetch_trending.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add youtube_trending_data.csv || echo "No changes to add"
          git commit -m "Updated trending video data" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

  extract-keywords:
    runs-on: ubuntu-latest
    needs: fetch-trending-data  # Ensure it runs after data fetching
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas nltk wordcloud matplotlib

      - name: Run Keyword Extraction Script
        run: python extract_keywords.py

      - name: Upload Word Cloud
        uses: actions/upload-artifact@v4  # Updated to latest version
        with:
          name: wordcloud
          path: wordcloud.png
